
export const colorsToChooseFrom = [
  {"name": "Blau", "value": "#0000ff"},
  {"name": "Dunkelgrün", "value": "#007f3f"},
  {"name": "Dunkelorange", "value": "#7f3500"},
  {"name": "Dunkelrot", "value": "#7f0000"},
  {"name": "Dunkelviolett", "value": "#7f3fff"},
  {"name": "Gelb", "value": "#ffff00"},
  {"name": "Grün", "value": "#00ff00"},
  {"name": "Hellgrün", "value": "#81ff7f"},
  {"name": "Hellorange", "value": "#ff9900"},
  {"name": "Hellrot", "value": "#ff7f7f"},
  {"name": "Hellviolett", "value": "#e900ff"},
  {"name": "Orange", "value": "#ffcc7f"},
  {"name": "Rosa", "value": "#ff008c"},
  {"name": "Rot", "value": "#ff0000"},
  {"name": "Lila", "value": "#800080"},
  {"name": "Türkis", "value": "#40e0d0"},
  {"name": "Magenta", "value": "#ff00ff"},
  {"name": "Olivgrün", "value": "#556b2f"},
  {"name": "Königsblau", "value": "#4169e1"},
  {"name": "Gold", "value": "#ffd700"},
  {"name": "Silber", "value": "#c0c0c0"},
  {"name": "Violett", "value": "#8a2be2"},
  {"name": "Koralle", "value": "#ff6b4a"}
];